name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: |
          npm install
          pip install -r requirements.txt
      - name: Run Python Program
        run: python main.py
